
services:
  web-dev:
    profiles: ["dev"]
    build: .
    container_name: node_express_dev
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]

  web-prod:
    profiles: ["prod"]
    build: .
    container_name: node_express_prod
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: ["npm", "start"]